"""course domain tables

Revision ID: 2c1cdcb0ade1
Revises: d9866525028c
Create Date: 2026-06-17 06:18:22.301083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c1cdcb0ade1'
down_revision: Union[str, Sequence[str], None] = 'd9866525028c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_usage_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('use_case', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_usage_logs_trace_id'), 'provider_usage_logs', ['trace_id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('intake_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('intake', 'outline_ready', 'building', 'ready', 'failed')", name='ck_courses_status'),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_courses_user_id_updated_at', 'courses', ['user_id', 'updated_at'], unique=False)
    op.create_table('course_units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_course_units_course_id_order_index', 'course_units', ['course_id', 'order_index'], unique=False)
    op.create_table('course_chapters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress', sa.Integer(), server_default='0', nullable=False),
    sa.Column('chosen_candidate_id', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('not_started', 'researching', 'ready', 'failed')", name='ck_course_chapters_status'),
    sa.ForeignKeyConstraint(['unit_id'], ['course_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_course_chapters_unit_id_order_index', 'course_chapters', ['unit_id', 'order_index'], unique=False)
    op.create_table('chapter_video_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('platform_video_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=True),
    sa.Column('is_chosen', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('discovery_source', sa.String(), nullable=False),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['course_chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chapter_video_candidates_chapter_id', 'chapter_video_candidates', ['chapter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chapter_video_candidates_chapter_id', table_name='chapter_video_candidates')
    op.drop_table('chapter_video_candidates')
    op.drop_index('ix_course_chapters_unit_id_order_index', table_name='course_chapters')
    op.drop_table('course_chapters')
    op.drop_index('ix_course_units_course_id_order_index', table_name='course_units')
    op.drop_table('course_units')
    op.drop_index('ix_courses_user_id_updated_at', table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_provider_usage_logs_trace_id'), table_name='provider_usage_logs')
    op.drop_table('provider_usage_logs')
    # ### end Alembic commands ###
