"""ai_messages add tool_json

Revision ID: 4574028ec452
Revises: ca78f2aa3592
Create Date: 2026-06-18 04:57:00.084989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4574028ec452'
down_revision: Union[str, Sequence[str], None] = 'ca78f2aa3592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_messages', sa.Column('tool_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_messages', 'tool_json')
    # ### end Alembic commands ###
