"""chapter_video_candidates add author_id

Revision ID: 8270c4106071
Revises: 8d27b84ff213
Create Date: 2026-06-18 12:10:30.441360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8270c4106071'
down_revision: Union[str, Sequence[str], None] = '8d27b84ff213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter_video_candidates', sa.Column('author_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapter_video_candidates', 'author_id')
    # ### end Alembic commands ###
