"""policy domain tables

Revision ID: b1c2d3e4f5a6
Revises: 7aba5ac01dc3
Create Date: 2026-07-24 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1c2d3e4f5a6'
down_revision: Union[str, Sequence[str], None] = '7aba5ac01dc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('need_text', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('search_status', sa.String(), server_default='searching', nullable=False),
    sa.Column('intake_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('coverage_end', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('selected_portfolio_id', sa.UUID(), nullable=True),
    sa.Column('on_chain_policy_id', sa.String(), nullable=True),
    sa.Column('open_tx', sa.String(), nullable=True),
    sa.Column('settle_tx', sa.String(), nullable=True),
    sa.Column('premium', sa.Numeric(), nullable=True),
    sa.Column('fee', sa.Numeric(), nullable=True),
    sa.Column('payout', sa.Numeric(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('intake', 'composing', 'proposed', 'funded', 'active', 'settled', 'failed')", name='ck_policies_status'),
    sa.CheckConstraint("search_status in ('searching', 'searched', 'failed')", name='ck_policies_search_status'),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_policies_user_id_updated_at', 'policies', ['user_id', 'updated_at'], unique=False)
    op.create_table('market_search_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('condition_id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('outcomes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outcome_prices', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('clob_token_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('volume', sa.Numeric(), nullable=True),
    sa.Column('liquidity', sa.Numeric(), nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_search_candidates_policy_id', 'market_search_candidates', ['policy_id'], unique=False)
    op.create_table('policy_portfolios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=True),
    sa.Column('premium_estimate', sa.Numeric(), nullable=True),
    sa.Column('expected_payout', sa.Numeric(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tier in ('conservative', 'balanced', 'aggressive')", name='ck_policy_portfolios_tier'),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_policy_portfolios_policy_id_order_index', 'policy_portfolios', ['policy_id', 'order_index'], unique=False)
    op.create_table('policy_positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('market_ref', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('entry_price_bps', sa.Integer(), nullable=False),
    sa.Column('weight_bps', sa.Integer(), nullable=False),
    sa.Column('resolution_date', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('ai_reason', sa.Text(), nullable=True),
    sa.Column('odds', sa.Numeric(), nullable=True),
    sa.Column('volume', sa.Numeric(), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("side in ('YES', 'NO')", name='ck_policy_positions_side'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['policy_portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_policy_positions_portfolio_id_order_index', 'policy_positions', ['portfolio_id', 'order_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_policy_positions_portfolio_id_order_index', table_name='policy_positions')
    op.drop_table('policy_positions')
    op.drop_index('ix_policy_portfolios_policy_id_order_index', table_name='policy_portfolios')
    op.drop_table('policy_portfolios')
    op.drop_index('ix_market_search_candidates_policy_id', table_name='market_search_candidates')
    op.drop_table('market_search_candidates')
    op.drop_index('ix_policies_user_id_updated_at', table_name='policies')
    op.drop_table('policies')
    # ### end Alembic commands ###
