"""chapter_video_candidates add like_count

Revision ID: ca78f2aa3592
Revises: 2c1cdcb0ade1
Create Date: 2026-06-17 07:38:24.282372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca78f2aa3592'
down_revision: Union[str, Sequence[str], None] = '2c1cdcb0ade1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter_video_candidates', sa.Column('like_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapter_video_candidates', 'like_count')
    # ### end Alembic commands ###
