"""add projects table and conversation project link

Revision ID: d9866525028c
Revises: da6eb582b6c8
Create Date: 2026-06-13 02:21:55.209458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9866525028c'
down_revision: Union[str, Sequence[str], None] = 'da6eb582b6c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_user_id_updated_at', 'projects', ['user_id', 'updated_at'], unique=False)
    op.add_column('ai_conversations', sa.Column('project_id', sa.UUID(), nullable=True))
    op.create_index('ix_ai_conversations_project_id_updated_at', 'ai_conversations', ['project_id', 'updated_at'], unique=False)
    op.create_foreign_key('ai_conversations_project_id_fkey', 'ai_conversations', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ai_conversations_project_id_fkey', 'ai_conversations', type_='foreignkey')
    op.drop_index('ix_ai_conversations_project_id_updated_at', table_name='ai_conversations')
    op.drop_column('ai_conversations', 'project_id')
    op.drop_index('ix_projects_user_id_updated_at', table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
