"""conversation composite indexes

Revision ID: da6eb582b6c8
Revises: e9487b3ea7dc
Create Date: 2026-06-12 00:13:05.807043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da6eb582b6c8'
down_revision: Union[str, Sequence[str], None] = 'e9487b3ea7dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_conversations_user_id'), table_name='ai_conversations')
    op.create_index('ix_ai_conversations_user_id_updated_at', 'ai_conversations', ['user_id', 'updated_at'], unique=False)
    op.drop_index(op.f('ix_ai_messages_conversation_id'), table_name='ai_messages')
    op.create_index('ix_ai_messages_conversation_id_created_at', 'ai_messages', ['conversation_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_messages_conversation_id_created_at', table_name='ai_messages')
    op.create_index(op.f('ix_ai_messages_conversation_id'), 'ai_messages', ['conversation_id'], unique=False)
    op.drop_index('ix_ai_conversations_user_id_updated_at', table_name='ai_conversations')
    op.create_index(op.f('ix_ai_conversations_user_id'), 'ai_conversations', ['user_id'], unique=False)
    # ### end Alembic commands ###
