"""ai_usage_logs: add cost_usd, conversation_id, composite user index

Revision ID: e9487b3ea7dc
Revises: 923d03079103
Create Date: 2026-06-10 14:23:30.641029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9487b3ea7dc'
down_revision: Union[str, Sequence[str], None] = '923d03079103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_usage_logs', sa.Column('cost_usd', sa.Numeric(precision=12, scale=8), nullable=True))
    op.add_column('ai_usage_logs', sa.Column('conversation_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_ai_usage_logs_user_id'), table_name='ai_usage_logs')
    op.create_index(op.f('ix_ai_usage_logs_conversation_id'), 'ai_usage_logs', ['conversation_id'], unique=False)
    op.create_index('ix_ai_usage_logs_user_id_created_at', 'ai_usage_logs', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_usage_logs_user_id_created_at', table_name='ai_usage_logs')
    op.drop_index(op.f('ix_ai_usage_logs_conversation_id'), table_name='ai_usage_logs')
    op.create_index(op.f('ix_ai_usage_logs_user_id'), 'ai_usage_logs', ['user_id'], unique=False)
    op.drop_column('ai_usage_logs', 'conversation_id')
    op.drop_column('ai_usage_logs', 'cost_usd')
    # ### end Alembic commands ###
