"""course_search_candidates and course search_status

Revision ID: eca285886d04
Revises: f4a2c9b1d7e3
Create Date: 2026-06-19 19:59:46.781297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eca285886d04'
down_revision: Union[str, Sequence[str], None] = 'f4a2c9b1d7e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_search_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('platform_video_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('author_id', sa.String(), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('like_count', sa.BigInteger(), nullable=True),
    sa.Column('comment_count', sa.BigInteger(), nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_course_search_candidates_course_id', 'course_search_candidates', ['course_id'], unique=False)
    op.add_column('courses', sa.Column('search_status', sa.String(), server_default='searching', nullable=False))
    # ### end Alembic commands ###
    # CHECK constraints are not emitted by autogenerate — apply them by hand.
    op.create_check_constraint(
        "ck_courses_search_status",
        "courses",
        "search_status in ('searching', 'searched', 'failed')",
    )
    # Widen the course status enum to include the new `organizing` state.
    op.drop_constraint("ck_courses_status", "courses", type_="check")
    op.create_check_constraint(
        "ck_courses_status",
        "courses",
        "status in ('intake', 'outline_ready', 'organizing', 'building', "
        "'ready', 'failed')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Restore the original (pre-organizing) status enum and drop the new check.
    op.drop_constraint("ck_courses_status", "courses", type_="check")
    op.create_check_constraint(
        "ck_courses_status",
        "courses",
        "status in ('intake', 'outline_ready', 'building', 'ready', 'failed')",
    )
    op.drop_constraint("ck_courses_search_status", "courses", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'search_status')
    op.drop_index('ix_course_search_candidates_course_id', table_name='course_search_candidates')
    op.drop_table('course_search_candidates')
    # ### end Alembic commands ###
